routes/web.php
<?php
/* CST-256 Database Application Programming III
 * Milestone 7
 * web, Version 5
 * Group CLC Project
 * 10/27/2019
 * This is used to register verious routes for our web application
 */

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes();
// Home Controller
Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/home', 'ProfileController@addInterests');

// REST *** Placed here for test purposes ***
Route::resource('/restjob','JobRestController');  // W/o id parameter: returns at most 15 job. W/ id parameter: return a single job with corresponding id. In JSON.
Route::resource('/restuser','UserRestController');  // W/o id parameter: returns at most 15 users. W/ id parameter: return a single user with corresponding id. In JSON.

//Route used to display the generic error page.
Route::get('error', function() {
    return view('error');
});

Route::group(
    array (
        'middleware' => ['auth']
    ),
    function () {

        // Profile Controller
        Route::get('/profile', 'ProfileController@index')->name('profile');
        Route::get('/profile/update', 'ProfileController@update')->name('update');
        Route::get('/portfolio', 'ProfileController@portfolio')->name('portfolio');
        Route::get('createPortfolio', 'ProfileController@createPortfolio')->name('createPortfolio');
        Route::get('/findJob','ProfileController@findJobView')->name('findJob');
        Route::get('/{id}/viewJob','ProfileController@viewJob')->name('viewJob');

        // Business Controller
        Route::get('/createJob','BusinessController@createJobView')->name('createJob');
        Route::post('/createJob','BusinessController@createJob')->name('createJob');
        Route::get('/registerCompany','BusinessController@registerCompanyView')->name('registerCompany');
        Route::post('/registerCompany','BusinessController@registerCompany')->name('registerCompany');
        Route::get('/openJobs','BusinessController@openJobsView')->name('openJobs');
        Route::get('/editJob','BusinessController@editJobView')->name('editJob');
        Route::post('/userApply','BusinessController@userApply')->name('userApply');
        Route::resource('company','BusinessController');

        // Admin Controller
        //Route::get('/admin', 'AdminController@index')->name('admin');
        Route::resource('admin', 'AdminController');
        Route::get('admin', 'AdminController@index')->name('admin');
        Route::get('create', 'AdminController@create')->name('create');
        Route::get('admin/{id}/editUserPortfolio', 'AdminController@editUserPortfolio')->name('editUserPortfolio');
        Route::post('admin/updatePortfolio/{id}', 'AdminController@updatePortfolio')->name('updatePortfolio');
        Route::delete('admin/destroyGroup/{id}', 'AdminController@destroyGroup')->name('destroyGroup');
        Route::get('admin/{id}/editGroup', 'AdminController@editGroup')->name('editGroup');
        Route::post('admin/updateGroup/{id}', 'AdminController@updateGroup')->name('updateGroup');

        // Group Controller
        Route::resource('group', 'GroupController');
        Route::get('{id}/groupPage', 'GroupController@goToGroup')->name('groupPage');
        Route::get('findGroups', 'GroupController@index')->name('findGroups');
        Route::post('findGroups', 'GroupController@joinGroup');
        Route::post('leaveGroups', 'GroupController@leaveGroup');
        Route::get('/createGroups', 'GroupController@createGroup')->name('createGroup');
        Route::post('createGroups', 'GroupController@createNewGroup')->name('createNewGroup');

        //Posts Controller
        Route::resource('post', 'PostController');
        Route::post('createPost', 'PostController@createNewPost')->name('createPost');
        //Route::get('newPost/{id}', ['as'=>'newPost', 'uses'=>'PostController@newPost']);
        Route::get('newPost/{id}', 'PostController@newPost')->name('newPost');
    }
    );

resources/views/createGroup.blade.php
<?php
/* CST-256 Database Application Programming III
 * Milestone 7
 * findGroups, Version 1
 * Group CLC Project
 * 10/27/2019
 * This will display a form where the user can create a group based on multiple interests.
 */
?>

@extends('layouts.app')

@section('title') Create Group @endsection

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col">
            <div class="card">
                <h4 class="card-header">Create Group</h4>
                    <div class="card-body">
                        <div class="row">
                            <div class="col">
                            @if ($errors->any())
      						<div class="alert alert-danger">
        						<ul>
            					@foreach ($errors->all() as $error)
              					<li>{{ $error }}</li>
            					@endforeach
        						</ul>
      							</div><br />
    							@endif
    							
    							<form method="post" action="{{route('createNewGroup')}}">
                    				@csrf   
                                  	<div class="form-group">
                                  		 <label for="groupname">Group Name:</label>
                                	 	 <input class="form-control" id="NAME" type="text" name="name">
                                	 	 <br>
                                		 <label for="postBody">Group Description:</label>
                                   	   	<textarea class="form-control" id="DESCRIPTION" name="description" rows="3"></textarea>
                                   	   	<br>
                                   	   <!-- <label for="groupinterest">Group Interest (Key Word):</label>
                                	 	<input class="form-control" id="INTEREST" type="text" name="interest"> -->
                                	 	<div class="form-group">
                                        <label for="industry">{{__('Industry: ')}}</label>
                                        <select class="form-control" id="INTEREST" name="interest">
                                            <option selected="selected" value=""></option>
                                            <option value="Aerospace">Aerospace</option>
                                            <option value="Agriculture">Agriculture</option>
                                            <option value="Art">Art</option>
                                            <option value="Construction">Construction</option>
                                            <option value="Education">Education</option>
                                            <option value="Energy">Energy</option>
                                            <option value="Entertainment">Entertainment</option>
                                            <option value="Food">Food</option>
                                            <option value="Hospitality">Hospitality</option>
                                            <option value="Manufacturing">Manufacturing</option>
                                            <option value="Medicine">Medicine</option>
                                            <option value="Mining">Mining</option>
                                            <option value="Music">Music</option>
                                            <option value="News">News</option>
                                            <option value="Pharmaceutical">Pharmaceutical</option>
                                            <option value="Technology">Technology</option>
                                            <option value="Telecommunication">Telecommunication</option>
                                            <option value="Transport">Transport</option>
                                        </select>
                                	 	
                                	 	
                                  	</div>
                                  	<button type="submit" class="btn btn-primary">Create</button>
                                </form>
    							
                            </div>
                        </div>
                    </div>
            </div>
        </div>
    </div>
</div>



<br>

<div class="col-sm-12">

  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div>
  @endif
</div>
@endsection

resources/views/editJob.blade.php
<?php
/* CST-256 Database Application Programming III
 * Milestone 7
 * editJob, Version 1
 * Group CLC Project
 * 10/27/2019
 * This will display a form where the job data can be edited and updated
 */
?>

@extends('layouts.app')

@section('title') Post A Job @endsection

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col">
                <div class="card">
                    <h3 class="card-header">Edit Job</h3>
                    <div class="card-body">
                        <div class="row">
                            <div class="col"><a href="#"><div id="background"></div></a></div>
                            <div class="col">
                                @if ($errors->any())
                                    <div class="alert alert-danger">
                                        <ul>
                                            @foreach ($errors->all() as $error)
                                                <li>{{ $error }}</li>
                                            @endforeach
                                        </ul>
                                    </div><br />
                                @endif
                                <form method="post" action="{{route('company.update',$job->id)}}">
                                    @method('PATCH')
                                    @csrf
                                    <div class="form-group">
                                        <label for="jobTitle">{{__('Job Title: ')}}</label>
                                        <input class="form-control" id="TITLE" type="text" name="title" value="{{$job->name}}">
                                    </div>
                                    <div class="form-group">
                                        <label for="responsibilities">{{__('Responsibilities: ')}}</label>
                                        <textarea class="form-control" rows="8" cols="80" name="responsibilities" id="RESPONSIBILITIES" >{{$job->responsibilities}}</textarea>
                                    </div>
                                    <div class="form-group">
                                        <label for="requirements">{{__('Requirements: ')}}</label>
                                        <textarea class="form-control" rows="8" cols="80" name="requirements" id="REQUIREMENTS">{{$job->requirements}}</textarea>
                                    </div>
                                    <div class="form-group">
                                        <label for="type">{{__('Type: ')}}</label>
                                        <select class="form-control" id="TYPE" name="type">
                                            <option selected="selected" value="{{$job->type}}">{{$job->type}}</option>
                                            <option value="Contract">Contract</option>
                                            <option value="Full Time">Full Time</option>
                                            <option value="Part Time">Part Time</option>
                                        </select>
                                    </div>
                                    
                                    <div class="form-group">
                                        <label for="industry">{{__('Industry: ')}}</label>
                                        <select class="form-control" id="INDUSTRY" name="industry">
                                        	<option selected="selected" value="{{$job->industry}}">{{$job->industry}}</option>
                                            <option value=""></option>
                                            <option value="Aerospace">Aerospace</option>
                                            <option value="Agriculture">Agriculture</option>
                                            <option value="Art">Art</option>
                                            <option value="Construction">Construction</option>
                                            <option value="Education">Education</option>
                                            <option value="Energy">Energy</option>
                                            <option value="Entertainment">Entertainment</option>
                                            <option value="Food">Food</option>
                                            <option value="Hospitality">Hospitality</option>
                                            <option value="Manufacturing">Manufacturing</option>
                                            <option value="Medicine">Medicine</option>
                                            <option value="Mining">Mining</option>
                                            <option value="Music">Music</option>
                                            <option value="News">News</option>
                                            <option value="Pharmaceutical">Pharmaceutical</option>
                                            <option value="Technology">Technology</option>
                                            <option value="Telecommunication">Telecommunication</option>
                                            <option value="Transport">Transport</option>
                                        </select>
                                    </div>
                                    
                                    <div class="form-group">
                                        <label for="salary">{{__('Salary: ')}}</label>
                                        <select class="form-control" id="SALARY" name="salary">
                                            <option selected="selected" value="{{$job->salary}}">{{$job->salary}}</option>
                                            <option value="$30000.00">$30,000 - $39,999</option>
                                            <option value="$40000.00">$40,000 - $49,999</option>
                                            <option value="$50000.00">$50,000 - $59,999</option>
                                            <option value="$60000.00">$60,000 - $69,999</option>
                                            <option value="$70000.00">$70,000 - $79,999</option>
                                            <option value="$80000.00">$80,000 - $89,999</option>
                                            <option value="$90000.00">$90,000 - $99,999</option>
                                            <option value="$100000.00">$100,000 - $109,999</option>
                                            <option value="$110000.00">$110,000 - $119,999</option>
                                            <option value="$120000.00">$120,000 - $129,999</option>
                                            <option value="$130000.00">$130,000 - $139,999</option>
                                            <option value="$140000.00">$140,000 - $149,999</option>
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <label for="city">{{__('City: ')}}</label>
                                        <input class="form-control" id="CITY" type="text" name="city" value="{{$job->city}}">
                                    </div>
                                    <div class="form-group">
                                        <label for="state">{{__('State: ')}}</label>
                                        <select class="form-control" id="STATE" name="state">
                                            <option value="{{$job->state}}" selected="selected">{{$job->state}}</option>
                                            <option value="AL">Alabama</option>
                                            <option value="AK">Alaska</option>
                                            <option value="AZ">Arizona</option>
                                            <option value="AR">Arkansas</option>
                                            <option value="CA">California</option>
                                            <option value="CO">Colorado</option>
                                            <option value="CT">Connecticut</option>
                                            <option value="DE">Delaware</option>
                                            <option value="DC">District Of Columbia</option>
                                            <option value="FL">Florida</option>
                                            <option value="GA">Georgia</option>
                                            <option value="HI">Hawaii</option>
                                            <option value="ID">Idaho</option>
                                            <option value="IL">Illinois</option>
                                            <option value="IN">Indiana</option>
                                            <option value="IA">Iowa</option>
                                            <option value="KS">Kansas</option>
                                            <option value="KY">Kentucky</option>
                                            <option value="LA">Louisiana</option>
                                            <option value="ME">Maine</option>
                                            <option value="MD">Maryland</option>
                                            <option value="MA">Massachusetts</option>
                                            <option value="MI">Michigan</option>
                                            <option value="MN">Minnesota</option>
                                            <option value="MS">Mississippi</option>
                                            <option value="MO">Missouri</option>
                                            <option value="MT">Montana</option>
                                            <option value="NE">Nebraska</option>
                                            <option value="NV">Nevada</option>
                                            <option value="NH">New Hampshire</option>
                                            <option value="NJ">New Jersey</option>
                                            <option value="NM">New Mexico</option>
                                            <option value="NY">New York</option>
                                            <option value="NC">North Carolina</option>
                                            <option value="ND">North Dakota</option>
                                            <option value="OH">Ohio</option>
                                            <option value="OK">Oklahoma</option>
                                            <option value="OR">Oregon</option>
                                            <option value="PA">Pennsylvania</option>
                                            <option value="RI">Rhode Island</option>
                                            <option value="SC">South Carolina</option>
                                            <option value="SD">South Dakota</option>
                                            <option value="TN">Tennessee</option>
                                            <option value="TX">Texas</option>
                                            <option value="UT">Utah</option>
                                            <option value="VT">Vermont</option>
                                            <option value="VA">Virginia</option>
                                            <option value="WA">Washington</option>
                                            <option value="WV">West Virginia</option>
                                            <option value="WI">Wisconsin</option>
                                            <option value="WY">Wyoming</option>
                                        </select>
                                    </div>
                                    <input type="hidden" name="company id" value="{{$job->company_id}}">
                                    <div class="row">
                                        <div class="col">

                                            <button class="btn btn-primary btn-block" type="submit" >Update Job</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/error.blade.php
<?php
/* CST-256 Database Application Programming III
 * Milestone 7
 * Error, Version 1
 * Group CLC Project
 * 10/26/2019
 * This error page will display if there is an error.
 */
?>

@extends('layouts.app')

@section('title') ProNet Error @endsection

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col">
                <div class="card">
                    <h3 class="card-header">ProNet Error</h3>
                    <div class="card-body">
                        <div class="row">
                            <div class="col"></div></a></div>
                            <div class="form-group">
                                 <label for="error">An Error has occured, please contact the site support.</label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/findGroups.blade.php
<?php
/* CST-256 Database Application Programming III
 * Milestone 7
 * findGroups, Version 1
 * Group CLC Project
 * 10/27/2019
 * This will display a form where a list of recommended groups will be displayed.
 */
?>

@extends('layouts.app')

@section('title') Find Groups @endsection

@section('content')
    <div class="container" >
        <div class="bg-light" id="findJobContainer">
            <div id="title" class="text-center text-dark">
                <h3>Connect with like minded people in a group based on your interests</h3>
            </div>
            <hr>
            @if($groups->count() == 0)
                <h4>No groups have been created yet.</h4>
                <p>Now seems like a great time to create one!</p>
            @endif
            @foreach($groups as $g)
                <div id="group" class="row">
                    <div class="col-lg">
                        <h4 ><a href="{{route('groupPage',['id'=>$g->id])}}" id="group-name">{{$g->name}}</a></h4>
                        <p>{{$g->description}}</p>
                        <p class="small">Interests in common: @if($g->inCommon == null) {{0}} @else {{$g->inCommon}} @endif </p>
                        @if(!in_array($g->name,$names))
                            <button class="btn-lg btn-outline-primary join" value="{{$g->name}}" >Join</button>
                        @else
                            <button class="btn-lg btn-primary joined" value="{{$g->name}}">Joined</button>
                        @endif
                    </div>
                </div>
                <hr>
            @endforeach
            <div class="text-right"><a class="btn btn-primary" href="{{ route('createGroup') }}">+ Create a Group</a></div>
        </div>
    </div>
    <div class="col-sm-12">

  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div>
  @endif
</div>
@endsection

resources/views/find_job.blade.php
<?php
/* CST-256 Database Application Programming III
 * Milestone 7
 * find_job, Version 1
 * Group CLC Project
 * 10/27/2019
 * This will display a form where a list of jobs will be displayed.
 */
?>

@extends('layouts.app')

@section('title') Find A Job @endsection

@section('content')
    <div class="container" >
        <div class="bg-light" id="findJobContainer">
            <div id="title">
                <h2>Find Your Dream Job</h2>
            </div>
            <hr>
            @if($jobs->count() == 0)
                <h4>No jobs have been posted yet.</h4>
                <p>Check back later!</p>
            
            
            @else
            <form method="get" action="{{route('findJob')}}">
             @csrf
            <div class="row">
                 <div class="col">
                 <div class="form-group">
            	<label for="jobtablefilter">{{__('Job Display: ')}}</label>
                    <select class="form-control" id="JOBTABLEFILTER" name="jobtablefilter">
                    	<option selected="selected" value=""></option>
                    	<option value="All">All Jobs</option>
                    	<option value="Recommended">Recommended Jobs</option>
                    </select> 
                    </div>
                    </div>
                 <div class="col">   
                 	<br>
                    <!-- <button class="btn btn-primary btn-block" type="submit" style="width: 25%">Submit</button> -->
                 </div>
                 <div class="col"></div>
            
            </div>
            
            
            <div class="row">
                 <div class="col">
            	<div class="form-group">
                    <label for="jobsearch">{{__('Job Search: ')}}</label>
                    <input class="form-control" id="JOBSEARCH" type="text" name="jobsearch">
                    
                    </div>
                    </div>
                 <div class="col">   
                 	<br>
                    <!-- <button class="btn btn-primary btn-block" type="submit" style="width: 25%">Submit</button> -->
                 </div>
                 <div class="col"></div>
            </div>  
            
            
            <div class="col">   
                 <br>
                 <button class="btn btn-primary btn-block" type="submit" style="width: 15%">Get Jobs</button>
            </div><hr>
            </form>
            
            
            @foreach($jobs as $j)
                <div id="job">
                    <h4><a href="{{route('viewJob',['id'=>$j->id])}}">{{$companies->find($j->company_id)->name}} - {{$j->name}}</a></h4>
                    <p class="small">{{$j->city}}, {{$j->state}}</p>
                </div>
                <hr>
            @endforeach
            @endif
        </div>
    </div>
@endsection

resources/views/home.blade.php
<?php
/* CST-256 Database Application Programming III
 * Milestone 7
 * home, Version 1
 * Group CLC Project
 * 10/27/2019
 * This will display the project home page
 */
?>

@extends('layouts.app')

@section('title') Home @endsection

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            @if(session('success'))
            <div class="alert alert-success" role="alert">
                {{session('success')}}
            </div>
            @endif
            <div class="card">
                <div class="card-header">Welcome {{Auth::user()->name}}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <p>New features added:</p>
                    <p>- Groups</p>
                    <p>- Interests</p>
                    <p>Select some interests below and we will recommend some groups you can join with people that share the same interests!</p>
                </div>
            </div>
                <br>
            <div class="bg-light border rounded">
                <div class="container text-center">
                    <br>
                    <h3> What are you interested in?</h3>
                    <br>
                    <div class="text-center" id="buttons">
                    @php($counter = 0)
                       @for($i = 0; $i < count($interests); $i++)
                           @if($counter < 5)
                                @php($counter+=1)
                            @else
                                @php($counter = 0)

                            @endif

                            <button class="btn btn-outline-{{$colors[$counter]}} butts">{{$interests[$i]->interest}}</button>

                        @endfor
                    
                        <!-- <button class="btn btn-outline-warning butts">Technology</button>
                        <button class="btn btn-outline-primary butts">Medicine</button>
                        <button class="btn btn-outline-danger butts">Music</button>
                        <button class="btn btn-outline-success butts">Art</button> -->
                    </div>
                    <br>
                    <a class="btn btn-outline-primary btn-block" href="{{route('findGroups')}}">Find Groups</a>
                    <br>
                    <div id="interests"></div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/openJobs.blade.php
<?php
/* CST-256 Database Application Programming III
 * Milestone 7
 * openJobs, Version 1
 * Group CLC Project
 * 10/27/2019
 * This will display a list of open jobs for the admin and business users.
 */
?>

@extends('layouts.app')

@section('title') Open Jobs @endsection

@section('content')
    <div class="container" >
            @if(session()->get('success'))
                <div class="alert alert-success">
                    {{ session()->get('success') }}
                </div>
            @endif
        <div class="bg-light" id="findJobContainer">
            <div id="title">
                <h2>Open Jobs</h2>
            </div>
            <hr>
            @if($jobs->count() == 0)
                @if(Auth::user()->usert!='Administrator')
                    <h4>No open jobs</h4>
                    <a class="small" href="{{route('createJob')}}">Create new job?</a>
                @else
                    <h4>No open jobs</h4>
                @endif
            @endif
            @foreach($jobs as $j)
                <div id="job">
                    <h4><a href="{{route('editJob',['jobID' => $j->id])}}"> @if(Auth::user()->usert=='Administrator'){{$company->find($j->company_id)->name}} - {{$j->name}} @else {{$j->name}} @endif </a></h4>
                    <p class="small">{{$j->city}}, {{$j->state}}</p>
                    <form action="{{ route('company.destroy', $j->id)}}" method="post">
                        @csrf
                        @method('DELETE')
                        <button class="btn btn-danger" type="submit">Close</button>
                    </form>
                </div>
                <hr>
            @endforeach
        </div>
    </div>
@endsection