routes/web.php
<?php
/* CST-256 Database Application Programming III
 * Milestone 7
 * web, Version 5
 * Group CLC Project
 * 10/27/2019
 * This is used to register verious routes for our web application
 */

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes();
// Home Controller
Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/home', 'ProfileController@addInterests');

// REST *** Placed here for test purposes ***
Route::resource('/restjob','JobRestController');  // W/o id parameter: returns at most 15 job. W/ id parameter: return a single job with corresponding id. In JSON.
Route::resource('/restuser','UserRestController');  // W/o id parameter: returns at most 15 users. W/ id parameter: return a single user with corresponding id. In JSON.

//Route used to display the generic error page.
Route::get('error', function() {
    return view('error');
});

Route::group(
    array (
        'middleware' => ['auth']
    ),
    function () {

        // Profile Controller
        Route::get('/profile', 'ProfileController@index')->name('profile');
        Route::get('/profile/update', 'ProfileController@update')->name('update');
        Route::get('/portfolio', 'ProfileController@portfolio')->name('portfolio');
        Route::get('createPortfolio', 'ProfileController@createPortfolio')->name('createPortfolio');
        Route::get('/findJob','ProfileController@findJobView')->name('findJob');
        Route::get('/{id}/viewJob','ProfileController@viewJob')->name('viewJob');

        // Business Controller
        Route::get('/createJob','BusinessController@createJobView')->name('createJob');
        Route::post('/createJob','BusinessController@createJob')->name('createJob');
        Route::get('/registerCompany','BusinessController@registerCompanyView')->name('registerCompany');
        Route::post('/registerCompany','BusinessController@registerCompany')->name('registerCompany');
        Route::get('/openJobs','BusinessController@openJobsView')->name('openJobs');
        Route::get('/editJob','BusinessController@editJobView')->name('editJob');
        Route::post('/userApply','BusinessController@userApply')->name('userApply');
        Route::resource('company','BusinessController');

        // Admin Controller
        //Route::get('/admin', 'AdminController@index')->name('admin');
        Route::resource('admin', 'AdminController');
        Route::get('admin', 'AdminController@index')->name('admin');
        Route::get('create', 'AdminController@create')->name('create');
        Route::get('admin/{id}/editUserPortfolio', 'AdminController@editUserPortfolio')->name('editUserPortfolio');
        Route::post('admin/updatePortfolio/{id}', 'AdminController@updatePortfolio')->name('updatePortfolio');
        Route::delete('admin/destroyGroup/{id}', 'AdminController@destroyGroup')->name('destroyGroup');
        Route::get('admin/{id}/editGroup', 'AdminController@editGroup')->name('editGroup');
        Route::post('admin/updateGroup/{id}', 'AdminController@updateGroup')->name('updateGroup');

        // Group Controller
        Route::resource('group', 'GroupController');
        Route::get('{id}/groupPage', 'GroupController@goToGroup')->name('groupPage');
        Route::get('findGroups', 'GroupController@index')->name('findGroups');
        Route::post('findGroups', 'GroupController@joinGroup');
        Route::post('leaveGroups', 'GroupController@leaveGroup');
        Route::get('/createGroups', 'GroupController@createGroup')->name('createGroup');
        Route::post('createGroups', 'GroupController@createNewGroup')->name('createNewGroup');

        //Posts Controller
        Route::resource('post', 'PostController');
        Route::post('createPost', 'PostController@createNewPost')->name('createPost');
        //Route::get('newPost/{id}', ['as'=>'newPost', 'uses'=>'PostController@newPost']);
        Route::get('newPost/{id}', 'PostController@newPost')->name('newPost');
    }
    );

resources/views/Admin/createUser.blade.php
<?php 
/* CST-256 Database Application Programming III
 * Milestone 2
 * createUser, Version 1
 * Group CLC Project
 * 09/22/2019
 * This will display a form where the admin can create a new user. 
 */
?>

@extends('layouts.app')

@section('title') Admin Menu @endsection

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col">
            <div class="card">
                <h4 class="card-header">Profile</h4>
                    <div class="card-body">
                        <div class="row">
                            <div class="col"><a href="#"><div id="background"></div></a></div>
                            <div class="col">
                            @if ($errors->any())
      						<div class="alert alert-danger">
        						<ul>
            					@foreach ($errors->all() as $error)
              					<li>{{ $error }}</li>
            					@endforeach
        						</ul>
      							</div><br />
    							@endif
                                <form method="POST" action="{{route('admin.store')}}">
                                	@csrf
                                    <div class="form-group">
                                        <label for="firstName">{{__('Name: ')}}</label>
                                        <input class="form-control" id="NAME" type="text" name="name">
                                    </div>
                                    <div class="form-group">
                                        <label for="phone">{{__('Phone: ')}}</label>
                                        <input class="form-control" id="PHONE" type="text" name="phone">
                                    </div>
                                    <div class="form-group">
                                        <label for="email">{{__('Email: ')}}</label>
                                        <input class="form-control" id="EMAIL" type="text" name="email">
                                    </div>
                                    <div class="form-group">
                                        <label for="password">{{__('Password: ')}}</label>
                                        <input class="form-control" id="PASSWORD" type="password" name="password">
                                    </div>
                                    <div class="form-group">
                                        <label for="gender">{{__('Gender: ')}}</label>
                                        <select class="form-control" id="MF" name="gender" >
                                            <option value=""></option>
                                            <option value="Male">Male</option>
                                            <option value="Female">Female</option>
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <label for="city">{{__('City: ')}}</label>
                                        <input class="form-control" id="CITY" type="text" name="city">
                                    </div>
                                    <div class="form-group">
                                        <label for="state">{{__('State: ')}}</label>
                                        <select class="form-control" id="STATE" name="state" >
                                            <option value=""></option>
                                            <option value="AL">Alabama</option>
                                            <option value="AK">Alaska</option>
                                            <option value="AZ">Arizona</option>
                                            <option value="AR">Arkansas</option>
                                            <option value="CA">California</option>
                                            <option value="CO">Colorado</option>
                                            <option value="CT">Connecticut</option>
                                            <option value="DE">Delaware</option>
                                            <option value="DC">District Of Columbia</option>
                                            <option value="FL">Florida</option>
                                            <option value="GA">Georgia</option>
                                            <option value="HI">Hawaii</option>
                                            <option value="ID">Idaho</option>
                                            <option value="IL">Illinois</option>
                                            <option value="IN">Indiana</option>
                                            <option value="IA">Iowa</option>
                                            <option value="KS">Kansas</option>
                                            <option value="KY">Kentucky</option>
                                            <option value="LA">Louisiana</option>
                                            <option value="ME">Maine</option>
                                            <option value="MD">Maryland</option>
                                            <option value="MA">Massachusetts</option>
                                            <option value="MI">Michigan</option>
                                            <option value="MN">Minnesota</option>
                                            <option value="MS">Mississippi</option>
                                            <option value="MO">Missouri</option>
                                            <option value="MT">Montana</option>
                                            <option value="NE">Nebraska</option>
                                            <option value="NV">Nevada</option>
                                            <option value="NH">New Hampshire</option>
                                            <option value="NJ">New Jersey</option>
                                            <option value="NM">New Mexico</option>
                                            <option value="NY">New York</option>
                                            <option value="NC">North Carolina</option>
                                            <option value="ND">North Dakota</option>
                                            <option value="OH">Ohio</option>
                                            <option value="OK">Oklahoma</option>
                                            <option value="OR">Oregon</option>
                                            <option value="PA">Pennsylvania</option>
                                            <option value="RI">Rhode Island</option>
                                            <option value="SC">South Carolina</option>
                                            <option value="SD">South Dakota</option>
                                            <option value="TN">Tennessee</option>
                                            <option value="TX">Texas</option>
                                            <option value="UT">Utah</option>
                                            <option value="VT">Vermont</option>
                                            <option value="VA">Virginia</option>
                                            <option value="WA">Washington</option>
                                            <option value="WV">West Virginia</option>
                                            <option value="WI">Wisconsin</option>
                                            <option value="WY">Wyoming</option>
                                        </select>
                                    </div>
                                    
	                                <div class="form-group">
                                        <label for="usert">{{__('Type Of User: ')}}</label>
                                        <select class="form-control" id="USERT" name="usert">
                                            <option value=""></option>
                                            <option value="Individual">Individual</option>
                                            <option value="Business">Business</option>
                                            <option value="Administrator">Administrator</option>
                                        </select>
                                    </div>
                                    
                                    <div class="form-group">
                                        <label for="status">{{__('Account Status: ')}}</label>
                                        <select class="form-control" id="STATUS" name="status">
                                            <option value=""></option>
                                            <option value="Active">Active</option>
                                            <option value="Suspended">Suspended</option>
                                        </select>
                                    </div>
                                    
                                    <div class="row">
                                        <div class="col">
                                        </div>
                                        <div class="col">
                                            <button class="btn btn-primary btn-block" type="submit" onclick="clickSave()">Add User</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/Admin/editGroup.blade.php
<?php
/* CST-256 Database Application Programming III
 * Milestone 4
 * editGroup, Version 1
 * Group CLC Project
 * 10/06/2019
 * This will display a form where the group data can be edited and updated
 */
?>

@extends('layouts.app')

@section('title') Admin Menu @endsection

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col">
            <div class="card">
                <h4 class="card-header">Edit Group</h4>
                    <div class="card-body">
                        <div class="row">
                            <div class="col"></div></a></div>
                            <div class="col">
                            @if ($errors->any())
      						<div class="alert alert-danger">
        						<ul>
            					@foreach ($errors->all() as $error)
              					<li>{{ $error }}</li>
            					@endforeach
        						</ul>
      							</div><br />
    						@endif
                                <form method="post" action="{{route('updateGroup', $group->id)}}">
                                	@csrf

                                    <div class="form-group">
                                        <label for="name">{{__('Group Name: ')}}</label>
                                        <input class="form-control" id="NAME" type="text" name="name" value="{{$group->name}}">
                                    </div>
                                    <div class="form-group">
                                        <label for="description">{{__('Group Description: ')}}</label>
                                        <input class="form-control" id="DESCRIPTION" type="text" name="description" value="{{$group->description}}">
                                    </div>

                                    <div class="row">
                                        <div class="col">
                                        </div>
                                        <div class="col">
                                            <button type="submit" class="btn btn-primary">Update</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
            </div>
        </div>
    </div>


@endsection

resources/views/Admin/editUser.blade.php
<?php
/* CST-256 Database Application Programming III
 * Milestone 3
 * editUser, Version 1
 * Group CLC Project
 * 09/22/2019
 * This will display a form where the user data can be edited and updated
 */
?>

@extends('layouts.app')

@section('title') Admin Menu @endsection

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col">
            <div class="card">
                <h4 class="card-header">Profile</h4>
                    <div class="card-body">
                        <div class="row">
                            <div class="col"><a href="#"><div id="background"></div></a></div>
                            <div class="col">
                            @if ($errors->any())
      						<div class="alert alert-danger">
        						<ul>
            					@foreach ($errors->all() as $error)
              					<li>{{ $error }}</li>
            					@endforeach
        						</ul>
      							</div><br />
    							@endif
                                <form method="post" action="{{route('admin.update', $user->id)}}">
                                	@csrf
                                	@method('PATCH')

                                    <div class="form-group">
                                        <label for="firstName">{{__('Name: ')}}</label>
                                        <input class="form-control" id="NAME" type="text" name="name" value="{{$user->name}}">
                                    </div>
                                    <div class="form-group">
                                        <label for="email">{{__('Email: ')}}</label>
                                        <input class="form-control" id="EMAIL" type="text" name="email" value="{{$user->email}}">
                                    </div>
                                    <div class="form-group">
                                        <label for="password">{{__('Password: ')}}</label>
                                        <input class="form-control" id="PASSWORD" type="password" name="password" value="{{$user->password}}">
                                    </div>
                                    <div class="form-group">
                                        <label for="city">{{__('City: ')}}</label>
                                        <input class="form-control" id="CITY" type="text" name="city" value="{{$user->city}}">
                                    </div>
                                    <div class="form-group">
                                        <label for="state">{{__('State: ')}}</label>
                                        <select class="form-control" id="STATE" name="state" >
                                        	<option selected="selected" value="{{$user->state}}">{{$user->state}}</option>
                                            <option value=""></option>
                                            <option value="AL">Alabama</option>
                                            <option value="AK">Alaska</option>
                                            <option value="AZ">Arizona</option>
                                            <option value="AR">Arkansas</option>
                                            <option value="CA">California</option>
                                            <option value="CO">Colorado</option>
                                            <option value="CT">Connecticut</option>
                                            <option value="DE">Delaware</option>
                                            <option value="DC">District Of Columbia</option>
                                            <option value="FL">Florida</option>
                                            <option value="GA">Georgia</option>
                                            <option value="HI">Hawaii</option>
                                            <option value="ID">Idaho</option>
                                            <option value="IL">Illinois</option>
                                            <option value="IN">Indiana</option>
                                            <option value="IA">Iowa</option>
                                            <option value="KS">Kansas</option>
                                            <option value="KY">Kentucky</option>
                                            <option value="LA">Louisiana</option>
                                            <option value="ME">Maine</option>
                                            <option value="MD">Maryland</option>
                                            <option value="MA">Massachusetts</option>
                                            <option value="MI">Michigan</option>
                                            <option value="MN">Minnesota</option>
                                            <option value="MS">Mississippi</option>
                                            <option value="MO">Missouri</option>
                                            <option value="MT">Montana</option>
                                            <option value="NE">Nebraska</option>
                                            <option value="NV">Nevada</option>
                                            <option value="NH">New Hampshire</option>
                                            <option value="NJ">New Jersey</option>
                                            <option value="NM">New Mexico</option>
                                            <option value="NY">New York</option>
                                            <option value="NC">North Carolina</option>
                                            <option value="ND">North Dakota</option>
                                            <option value="OH">Ohio</option>
                                            <option value="OK">Oklahoma</option>
                                            <option value="OR">Oregon</option>
                                            <option value="PA">Pennsylvania</option>
                                            <option value="RI">Rhode Island</option>
                                            <option value="SC">South Carolina</option>
                                            <option value="SD">South Dakota</option>
                                            <option value="TN">Tennessee</option>
                                            <option value="TX">Texas</option>
                                            <option value="UT">Utah</option>
                                            <option value="VT">Vermont</option>
                                            <option value="VA">Virginia</option>
                                            <option value="WA">Washington</option>
                                            <option value="WV">West Virginia</option>
                                            <option value="WI">Wisconsin</option>
                                            <option value="WY">Wyoming</option>
                                        </select>
                                    </div>
                                    @if($user->usert == 'Individual')
                                        <div class="form-group">
                                            <label for="phone">{{__('Phone: ')}}</label>
                                            <input class="form-control" id="PHONE" type="text" name="phone" disabled value="{{$user->phone}}">
                                        </div>
                                        <div class="form-group">
                                            <label for="gender">{{__('Gender: ')}}</label>
                                            <select class="form-control" id="MF" disabled name="gender">
                                                <option selected="selected" value="{{$user->gender}}">{{$user->gender}}</option>
                                                <option value=""></option>
                                                <option value="Male">Male</option>
                                                <option value="Female">Female</option>
                                            </select>
                                        </div>
                                    @elseif($user->usert == 'Business')
                                        <div class="form-group">
                                            <label for="type">{{__('Type of Company: ')}}</label>
                                            <textarea rows="8" cols="80" class="form-control" id="TYPE" type="text" name="type"></textarea>
                                        </div>
                                        <div class="form-group">
                                            <label for="description">{{__('Description of Company: ')}}</label>
                                            <textarea rows="8" cols="80" class="form-control" id="DESCRIPTION" type="text" name="description"></textarea>
                                        </div>
                                    @endif
	                                <div class="form-group">
                                        <label for="usert">{{__('Type Of User: ')}}</label>
                                        <select class="form-control" id="USERT" name="usert" >
                                        	<option selected="selected" value="{{$user->usert}}">{{$user->usert}}</option>
                                            <option value=""></option>
                                            <option value="Individual">Individual</option>
                                            <option value="Business">Business</option>
                                            <option value="Administrator">Administrator</option>
                                        </select>
                                    </div>

                                    <div class="form-group">
                                        <label for="status">{{__('Account Status: ')}}</label>
                                        <select class="form-control" id="STATUS" name="status" >
                                        	<option selected="selected" value="{{$user->status}}">{{$user->status}}</option>
                                            <option value=""></option>
                                            <option value="Active">Active</option>
                                            <option value="Suspended">Suspended</option>
                                        </select>
                                    </div>

                                    <div class="row">
                                        <div class="col">
                                        </div>
                                        <div class="col">
                                            <button type="submit" class="btn btn-primary">Update</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
            </div>
        </div>
    </div>
</div>


@endsection

resources/views/Admin/index.blade.php
<?php 
/* CST-256 Database Application Programming III
 * Milestone 3
 * Admin index, Version 1
 * Group CLC Project
 * 09/29/2019
 * This will display the admin view with a table of users to create, read, update and delete. Also updates the user portfolio 
 */
?>

@extends('layouts.app')

@section('title') Admin Menu @endsection

@section('content')
<a class="btn btn-primary btn-lg" href="{{ route('create') }}" role="button">Create User</a>
<p>
<div class="container">
    <div class="row justify-content-center">
		<div class="row">
			<div class="card">
    			<h1 class="card-header">Users</h1>    
  				<table class="table table-striped">
    				<thead>
        				<tr>
          				<td>ID</td>
          				<td>Name</td>
          				<td>Email</td>
          				<td>Type</td>
          				<td>Status</td>
          				<td colspan = 2>Actions</td>
        				</tr>
    				</thead>
    				<tbody>
        				@foreach($users as $User)
        				<tr>
            				<td>{{$User->id}}</td>
            				<td>{{$User->name}}</td>
            				<td>{{$User->email}}</td>
            				<td>{{$User->usert}}</td>
            				<td>{{$User->status}}</td>
            				<td>
                			<!-- Split button -->
							<div class="btn-group">
  								<button type="button" class="btn btn-primary">Edit</button>
  								<button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    								<span class="caret"></span>
    								<span class="sr-only">Toggle Dropdown</span>
  								</button>
  								<ul class="dropdown-menu">
    								<li><a href="{{ route('admin.edit',$User->id)}}">User Profile</a></li>
    								<li><a href="{{ route('editUserPortfolio',$User->id)}}">User ePortfolio</a></li>
  								</ul>
							</div>
                			<!-- <a href="{{ route('admin.edit',$User->id)}}" class="btn btn-primary">Edit</a> -->
            				</td>
            				<td>
                			<form action="{{ route('admin.destroy', $User->id)}}" method="post">
                  				@csrf
                  				@method('DELETE')
                  			<button class="btn btn-danger" type="submit">Delete</button>
                			</form>
            				</td>

        				</tr>
        				@endforeach
    				</tbody>
  				</table>
			</div>
		</div>
	</div>
</div>
<br>


<div class="container">
    <div class="row justify-content-center">
		<div class="row">
			<div class="card">
    			<h1 class="card-header">Groups</h1>    
  				<table class="table table-striped">
    				<thead>
        				<tr>
          				<td>ID</td>
          				<td>Name</td>
          				<td>Details</td>
          				<td colspan = 2>Actions</td>
        				</tr>
    				</thead>
    				<tbody>
        				@foreach($groups as $Group)
        				<tr>
            				<td>{{$Group->id}}</td>
            				<td>{{$Group->name}}</td>
            				<td>{{$Group->description}}</td>
            				<td>
                			<a href="{{ route('editGroup',$Group->id)}}" class="btn btn-primary">Edit</a>
                			@csrf
            				</td>
            				<td>
                			<form action="{{ route('destroyGroup', $Group->id)}}" method="post">
                  				@csrf
                  				@method('DELETE')
                  			<button class="btn btn-danger" type="submit">Delete</button>
                			</form>
            				</td>

        				</tr>
        				@endforeach
    				</tbody>
  				</table>
			</div>
		</div>
	</div>
</div>
<br>


<div class="col-sm-12">

  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div>
  @endif
</div>
@endsection